# See https://taskfile.dev/
#
# e.g. `task -w test-cov`
version: "3"

tasks:
  build:
    cmds:
      - go build ./...
    sources:
      - "**/*.go"

  lint:
    cmds:
      - golangci-lint run ./...
    sources:
      - "**/*.go"

  test:
    cmds:
      - go test ./...
    sources:
      - "**/*.go"
      - "**/testdata/*"
      - "**/tmpl/*"

  test-cov:
    cmds:
      - go test -cover ./...
    sources:
      - "**/*.go"
      - "**/testdata/*"
      - "**/tmpl/*"

  test-cov-html:
    cmds:
      - go test -coverprofile=./coverage.out ./...
      - go tool cover -html=./coverage.out -o ./coverage.html
    sources:
      - "**/*.go"
      - "**/testdata/*"
      - "**/tmpl/*"
